### ISSUE TITLE
New epel package URL

### ISSUE THREAD

**Issue by hegyre** [saltstack-formulas/epel-formula#42] opened 2017-12-18 22:27 UTC
Hello,

Got this issue with a fresh CentOS 7.4:

MinionError: Error: HTTP 404: Not Found reading http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-11.noarch.rpm

After digging a bit, at appears that they've updated the URL.

They have added a Packages/ folder, like this:

http://download.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

Wouldn't be simpler to set the URL to the following one instead ?
http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

Edit: same thing for epel 6-8, and same url proposal:
http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

**Comment by athienem** [comment] 2018-03-11 22:11
While the idea is great to fetch the release packages from the more stable URL under http://dl.fedoraproject.org/pub/epel/ the problem is, that this is a centralized URL pointing to the Red Hat datacenter in Phoenix, Arizona.

The download.fedoraproject.org URLs get redirected to the global mirror network with a mirror much closer to the requesting system...
As such, I think it is worth keeping the download.fpo links, even if they are somewhat brittle.

**Comment by hegyre** [comment] 2018-09-05 16:10
Thanks for the URL Update @ixs 

Also agree with you @athienem 

Just tested the formula with the latest commit in date, it's working fine.

I think this issue can be closed.

Thx guys!

**Comment by javierbertoli** [comment] 2018-09-05 16:27
Thanks, guys. Closing.

**Closed by javierbertoli** 2018-09-05 16:27 UTC
