### ISSUE TITLE
Specified md5 checksum for /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL (58fa8ae27c89f37b08429f04fd4a88cc) does not match actual checksum (d41d8cd98f00b204e9800998ecf8427e)

### ISSUE THREAD

**Issue by porunov** [saltstack-formulas/epel-formula#39] opened 2017-10-12 15:37 UTC
OS: CentOS 7.3
SaltStack: 2017.7.1

Pillar:
```
epel:
  disabled: false
  testing: false
  release: 7-10
```

Output:
```
192.168.0.106:
----------
          ID: install_pubkey_epel
    Function: file.managed
        Name: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
      Result: False
     Comment: Specified md5 checksum for /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL (58fa8ae27c89f37b08429f04fd4a88cc) does not match actual checksum (d41d8cd98f00b204e9800998ecf8427e)
     Started: 18:33:58.646828
    Duration: 736.462 ms
     Changes:   
              ----------
              diff:
                  New file
----------
          ID: epel_release
    Function: pkg.installed
      Result: False
     Comment: One or more requisite failed: epel.install_pubkey_epel
     Changes:   
----------
          ID: set_pubkey_epel
    Function: file.replace
        Name: /etc/yum.repos.d/epel.repo
      Result: False
     Comment: One or more requisite failed: epel.epel_release
     Changes:   
----------
          ID: set_gpg_epel
    Function: file.replace
        Name: /etc/yum.repos.d/epel.repo
      Result: False
     Comment: One or more requisite failed: epel.epel_release
     Changes:   
----------
          ID: enable_epel
    Function: file.replace
        Name: /etc/yum.repos.d/epel.repo
      Result: False
     Comment: /etc/yum.repos.d/epel.repo: file not found
     Started: 18:33:59.773401
    Duration: 0.495 ms
     Changes:   
----------
          ID: disable_epel_testing
    Function: file.replace
        Name: /etc/yum.repos.d/epel-testing.repo
      Result: False
     Comment: /etc/yum.repos.d/epel-testing.repo: file not found
     Started: 18:33:59.773976
    Duration: 0.313 ms
     Changes:   

Summary for 192.168.0.106
------------
Succeeded: 0 (changed=1)
Failed:    6
------------
Total states run:     6
Total run time: 737.270 ms
ERROR: Minions returned with non-zero exit code
```

**Comment by supertylerc** [comment] 2017-10-12 23:12
Can confirm on CentOS 7.4 and Salt 2017.7.2.  Same hash is detected.

**Comment by supertylerc** [comment] 2017-10-12 23:58
Might be related to saltstack/salt#44013.

**Comment by supertylerc** [comment] 2017-10-13 02:24
Not sure what @porunov was running into since he was running 2017.7.1, but I was definitely hitting the aforementioned bug in 2017.7.2.  I pinned my CentOS minion to the official repo's 2017.7.1 version and everything was fine.

**Comment by chrisrasco** [comment] 2017-10-16 16:23
Definitely hitting this on 2017.7.2 at the moment:

`----------
          ID: install_pubkey_epel
    Function: file.managed
        Name: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
      Result: False
     Comment: Specified md5 checksum for /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL (58fa8ae27c89f37b08429f04fd4a88cc) does not match actual checksum (d41d8cd98f00b204e9800998ecf8427e)
     Started: 16:19:58.335262
    Duration: 275.942 ms
     Changes:
              ----------
              diff:
                  New file
----------
`

**Comment by dseira** [comment] 2017-10-16 19:25
@chrisrasco @supertylerc Let me make some tests.

**Comment by dseira** [comment] 2017-10-24 15:58
I'm testing but without success; in my machine it doesn't appear that error. I will continue with the tests.

**Comment by SMillerDev** [comment] 2018-01-10 12:26
I found that changing it to an sha256 hash worked for me. Can anyone confirm?

**Comment by solomongifford** [comment] 2018-01-12 22:21
The hash "d41d8cd98f00b204e9800998ecf8427e" is for an empty file - the bug is related to.  The repo has the correct hash.  

For example, the following will create an empty file /tmp/a:

`salt '*' file.manage_file /tmp/a '' '{}' http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 '{hash_type: 'md5', 'hsum': asdf}' root root '755' base '' skip_verify=True`

**Comment by solomongifford** [comment] 2018-01-12 23:04
I've confirmed the issue above is the issue and will be fixed in saltstack 2017.7.3. 

Workaround 1: Apply the following change to your minions and restart.
https://github.com/saltstack/salt/pull/44016/files#diff-4fca4b4bfdd1a281410595e9fe57f36a

Workaround 2:  Add the following pillar data:

`epel:
   pubkey: https://mirrors.dotsrc.org/fedora-epel/RPM-GPG-KEY-EPEL-7`

**Comment by hegyre** [comment] 2018-09-05 13:46
@javierbertoli ,
Had the same issue before your PR #45 with 2017.7.2

After updating to the last formula commit, no more issues. I think you can really close this issue

**Comment by javierbertoli** [comment] 2018-09-05 14:10
Thanks, @hegyre

**Closed by javierbertoli** 2018-09-05 14:10 UTC
